server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: whales

  datasource:
    url: jdbc:postgresql://localhost:5432/whales_db
    username: postgres
    password: tnghks123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

jwt:
  secret: ajkd-seofkf-wkc-woer-aloesr-ken-seknv-aseoie-wef
  access:
    expiration: 900000 # 15m