server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: whales

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

jwt:
  secret: ${JWT_SECRET}
  access:
    expiration: ${JWT_ACCESS_EXPIRATION}

oauth2:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    token-uri: ${GOOGLE_TOKEN_URI}
    userinfo-uri: ${GOOGLE_USERINFO_URI}
    redirect-uri: ${GOOGLE_REDIRECT_URI}