server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: whales
  datasource:
    url: jdbc:postgresql://localhost:5432/whales_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update    # ??: update / ??: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always   # schema.sql, data.sql ???
